name: Validate Agentic Flows

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup tools
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl git yamllint bats

      - name: Make scripts executable
        run: |
          chmod +x */*.sh 2>/dev/null || true

      - name: Run tests (Bats)
        run: |
          bats -r tests

      - name: Legacy test harness
        run: |
          bash ./test-workflows.sh | cat